// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc6LiiIRsDYnLpHiaIXLdx0Ohd4AH_pTU',
    appId: '1:595817390727:web:a4bf0229984b0af1fe4e22',
    messagingSenderId: '595817390727',
    projectId: 'flutter-chat-app-5a84c',
    authDomain: 'flutter-chat-app-5a84c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5a84c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASTDwzh75gn97aBX4HuH1vjH1FY3CfyKk',
    appId: '1:595817390727:android:7a43ac09348a02aafe4e22',
    messagingSenderId: '595817390727',
    projectId: 'flutter-chat-app-5a84c',
    storageBucket: 'flutter-chat-app-5a84c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPRGbihBjHg46m9pR4OEpFJAsjyhyDB2U',
    appId: '1:595817390727:ios:90d5589415bbf4aafe4e22',
    messagingSenderId: '595817390727',
    projectId: 'flutter-chat-app-5a84c',
    storageBucket: 'flutter-chat-app-5a84c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPRGbihBjHg46m9pR4OEpFJAsjyhyDB2U',
    appId: '1:595817390727:ios:4230f5579215d968fe4e22',
    messagingSenderId: '595817390727',
    projectId: 'flutter-chat-app-5a84c',
    storageBucket: 'flutter-chat-app-5a84c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
